[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bash -c 'pnpm daemon & pnpm --filter @b1dz/web start'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
